<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-363D707P" failures="1" tests="6" name="Test" time="0.129" errors="0" timestamp="2025-07-14T12:25:53 IST">
  <testcase classname="browser_agnostic_feature.retryAnalyzer.Demo_Test" name="testFail" time="0.017">
    <skipped/>
  </testcase> <!-- testFail -->
  <testcase classname="browser_agnostic_feature.retryAnalyzer.Demo_Test" name="testFail" time="0.003">
    <skipped/>
  </testcase> <!-- testFail -->
  <testcase classname="browser_agnostic_feature.retryAnalyzer.Demo_Test" name="testFail" time="0.002">
    <skipped/>
  </testcase> <!-- testFail -->
  <testcase classname="browser_agnostic_feature.retryAnalyzer.Demo_Test" name="testFail" time="0.003">
    <failure type="java.lang.AssertionError" message="Intentional failure!">
      <![CDATA[java.lang.AssertionError: Intentional failure!
at browser_agnostic_feature.retryAnalyzer.Demo_Test.testFail(Demo_Test.java:22)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1604)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- testFail -->
  <testcase classname="browser_agnostic_feature.retryAnalyzer.Demo_Test" name="testPass" time="0.002"/>
  <testcase classname="browser_agnostic_feature.retryAnalyzer.Demo_Test" name="skipTest" time="0.0">
    <skipped/>
  </testcase> <!-- skipTest -->
</testsuite> <!-- Test -->
